name: Comment issues when closed # the name of the workflow
on: # This action will trigger when an issue is reopened or opened.
  issues:
    types:
      - closed
jobs: # the first job is named as label_issues 
  label_issues
